name: morbo
services:
  pwa:
    build: .
    image: ghcr.io/morbo-org/pwa:latest
    develop:
      watch:
        - path: .
          action: rebuild
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  traefik:
    external: true
