name: morbo
services:
  pwa:
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: pwa/src
          target: /pwa/src
          action: sync
        - path: pwa/index.html
          target: /pwa/index.html
          action: sync
        - path: pwa/package.json
          action: rebuild
        - path: pwa/vite.config.ts
          action: rebuild
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  traefik:
    external: true
